'use client'

import { useRef } from "react";
import { useReactToPrint } from 'react-to-print'

export default function App() {
    const componentRef = useRef(null);
    const handlePrint = useReactToPrint({
      content: () => componentRef.current,
      documentTitle: 'sample Tile',
    });
  
    return (
      <>
        <div className="App" ref={componentRef}>
          <div className="header">
            <span className="logo">REAs</span>
            <nav>
              <span>Blog</span>
              <span>Categories</span>
              <span>Tags</span>
            </nav>
          </div>
          <div className="hero-section">
            <h1>The Joys of Buying Over Building</h1>
          </div>
          <main>
            <h2 className="features-title">Some features</h2>
            <div className="features">
              <span className="active">House 1</span>
              <span>House 2</span>
              <span>House 3</span>
            </div>
            <p>
              In the grand game of acquiring a new abode, the age-old debate
              between buying an existing house and building a brand-new one
              continues to captivate prospective homeowners. Both options have
              their merits, but lets take a lighthearted stroll through the perks
              of opting for a pre-built dwelling.
            </p>
            <p>
              Then theres the joy of exploring neighborhoods with character and
              history. Buying a house often means settling into an established
              community, complete with charming local spots and friendly
              neighbors. Sure, you might not have personally picked out every
              detail of your home, but theres a unique charm in discovering the
              stories embedded in its walls and the quirks that come with a house
              thats been lived in.
            </p>
            <p>
              In the end, whether youre swiping right on a charming existing home
              or swaying to the rhythm of your own construction symphony, the
              decision between buying and building is a personal one. But hey,
              theres something undeniably delightful about stepping into a house
              and immediately feeling at home no hard hat required.
            </p>
            <p className="lower">Article generated by ChatGPT</p>
          </main>
        </div>
        <button className='bg-sky-400 p-3 rounded' onClick={handlePrint}>Send</button>
      </>
    );
  }